[project]
name = "vrnetlab"
version = "0.1.0"
description = "vrnetlab fork for Containerlab integration"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "scrapli>=2024.7.30.post1",
]
